### ISSUE TITLE
Les statistiques ne s'affichent pas

### ISSUE THREAD

**Issue by bboisvert** [Greenwood-Consulting/CinePS#39]
Bug constaté en prod

Reproduire le bug :
- Faire des propositions
- Certains utilisateurs ont voté mais pas tous
- Aller sur la page des statistiques avec un utilisateur qui n'a pas voté

Les graphiques ne s'affichent pas. En cause : le premier (Classement des films de la semaine)

![image](https://user-images.githubusercontent.com/14802504/216620053-c2be412b-1b5b-4022-a344-6825205ae5dc.png)

![image](https://user-images.githubusercontent.com/14802504/216620303-c75ae7a9-2cef-4a09-996e-9386dd633683.png)

**Comment by merliin93** [comment]
Le problème vient des apostrophes, il sera résolu pour la prochaine release.
