### ISSUE TITLE
Probleme statistique

### ISSUE THREAD

**Issue by merliin93** [Greenwood-Consulting/CinePS#43]
Les affichages des statistiques ne s'affichent.(sûrement dû à cause d'une virgule)

![image](https://user-images.githubusercontent.com/99196681/221551952-794b32bb-5b59-4530-8db7-ccd63b46a2f5.png)

**Comment by fmistdev** [comment]
Le problème est à la ligne:

`echo "['" . $data_proposeurs[$i]['Proposeur'] . "'," . $data_proposeurs[$i]['nombre'] . "],";`

Si le prénom d'un proposeur contient une apostrophe, cela créé une erreur.

le ligne suivante corrige le problème:

`echo "['" . addslashes($data_proposeurs[$i]['Proposeur']) . "'," . $data_proposeurs[$i]['nombre'] . "],";`
