### ISSUE TITLE
Classements sur la page statistiques

### ISSUE THREAD

**Issue by DuncanTls** [Greenwood-Consulting/CinePS#78]
Quelques suggestions sur la page statistiques : 

### Le votant le plus satisfait.
Je pense que l'explication de la section peut être améliorée.
Voici une proposition.
Ce classement se base sur **l'ordre** des films proposé par chaque utilisateur lors de la phase de vote.
Il mesure à quel point le film sélectionné à chaque PS est cohérent avec les choix de chaque utilisateur.
Un **score bas** indique que les films sont globalement en adéquation avec ses choix, un **score haut** indique que les films sont globalement  en inadéquation avec ses choix.

### Le spectateur le plus satisfait.
Ce classement se base sur **la note** attribuée par chaque utilisateur aux films vus en PS.
Il mesure à quel point le spectateur a apprécié, en moyenne, les films qu'il a pu visionner.
Il correspond à la moyenne des notes qu'il a attribué aux différents films sur sa page de profil ou sur la page historique.

### Le proposeur le plus satisfait (ou satisfaisant....)
C'est une nouvelle proposition de classement. 
La méthode de calcul est de prendre pour chaque proposeur la moyenne des **notes** attribuées aux films qu'il a proposé en PS par les autres membres de la PS (en excluant le vote du proposeur lui meme).
Une proposition d'explication de la section : 
Ce classement se base sur **les notes** attribuées par les spectateurs vis à vis des films d'un proposeur donné.
Il mesure a quel point les films proposés par le proposeur et visionnés en PS ont été appréciés. 
Il correspond à la moyenne des notes attribuées par les spectateurs aux films d'un proposeur donné, en excluant la note du proposeur lui-même.

**Comment by bboisvert** [comment]
Salut,
Merci pour tes suggestions. J'ai modifié la page statistiques en m'inspirant de tes suggestions. Ce sera disponible dans la prochaine release.
Pour le 3eme point que tu as appelé "Le proposeur le plus satisfait (ou satisfaisant....)", cette statistique sera présente et s'appellera "Le meilleur proposeur"
